const SHOW_NOT_ACTIVATED_MODAL = "SHOW_NOT_ACTIVATED_MODAL";

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const CHECK_STATE = "CHECK_STATE";
const SHOW_FORGOT_PASSWORD = "SHOW_FORGOT_PASSWORD";

const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
const SHOW_CREATE_CHAT_MODAL = "SHOW_CREATE_CHAT_MODAL";
const SHOW_ADD_USER_MODAL = "SHOW_ADD_USER_MODAL";
const SHOW_MANAGE_CHAT_MODAL = "SHOW_MANAGE_CHAT_MODAL";
const SHOW_CHAT_DATA = "SHOW_CHAT_DATA";
const SHOW_USER_INFO = "SHOW_USER_INFO";

const SHOW_USER_MENU = "SHOW_USER_MENU";
const SET_USER_MENU_BUTTON_REF = "SET_USER_MENU_BUTTON_REF";

const CHANGE_CHAT_LIST_SIZE = "CHANGE_CHAT_LIST_SIZE";
const SHOW_USER_SETTINGS = "SHOW_USER_SETTINGS";

const SET_DELETED_MESSAGE_ID = "SET_DELETED_MESSAGE_ID";
const RESET_DELETED_MESSAGE_ID = "RESET_DELETED_MESSAGE_ID";

const SET_UPDATED_MESSAGE_ID = "SET_UPDATED_MESSAGE_ID";
const RESET_UPDATED_MESSAGE_ID = "RESET_UPDATED_MESSAGE_ID";

const SET_UPDATED_MESSAGE_PREV_STATE = "SET_UPDATED_MESSAGE_PREV_STATE";
const SET_UPDATED_MESSAGE_NEW_STATE = "SET_UPDATED_MESSAGE_NEW_STATE";
const RESET_UPDATED_MESSAGE_PREV_STATE = "RESET_UPDATED_MESSAGE_PREV_STATE";
const RESET_UPDATED_MESSAGE_NEW_STATE = "RESET_UPDATED_MESSAGE_NEW_STATE";

const SET_CURRENT_CHAT_RIGHTS = "SET_CURRENT_CHAT_RIGHTS";

const SET_ACTIVE_USERS = "SET_ACTIVE_USERS";

const SET_ERROR_CODE_AND_SHOW_ERROR_MODAL = "SET_ERROR_CODE_AND_SHOW_ERROR_MODAL";

const SHOW_MENU = "SHOW_MENU";
const SET_MENU_BUTTON_REF = "SET_MENU_BUTTON_REF";

const SHOW_COOKIE_INFO = "SHOW_COOKIE_INFO";
const SHOW_SUCCESSFUL_VERIFICATION = "SHOW_SUCCESSFUL_VERIFICATION";

const SHOW_CUSTOM_THEME_MODAL = "SHOW_CUSTOM_THEME_MODAL";
const CHECK_THEME = "CHECK_THEME";
const SET_LIGHT_THEME = "SET_LIGHT_THEME";
const SET_DARK_THEME = "SET_DARK_THEME";
const SET_CUSTOM_THEME = "SET_CUSTOM_THEME";

export {
  SHOW_NOT_ACTIVATED_MODAL,
  LOGIN,
  LOGOUT,
  SHOW_FORGOT_PASSWORD,
  CHECK_STATE,
  SET_ACTIVE_CHAT,
  SHOW_CREATE_CHAT_MODAL,
  SHOW_ADD_USER_MODAL,
  SHOW_MANAGE_CHAT_MODAL,
  SHOW_CHAT_DATA,
  SHOW_USER_INFO,
  SHOW_USER_SETTINGS,
  SHOW_USER_MENU,
  SET_USER_MENU_BUTTON_REF,
  CHANGE_CHAT_LIST_SIZE,
  SET_DELETED_MESSAGE_ID,
  RESET_DELETED_MESSAGE_ID,
  SET_UPDATED_MESSAGE_ID,
  RESET_UPDATED_MESSAGE_ID,
  SET_UPDATED_MESSAGE_PREV_STATE,
  SET_UPDATED_MESSAGE_NEW_STATE,
  RESET_UPDATED_MESSAGE_PREV_STATE,
  RESET_UPDATED_MESSAGE_NEW_STATE,
  SET_CURRENT_CHAT_RIGHTS,
  SET_ERROR_CODE_AND_SHOW_ERROR_MODAL,
  SHOW_MENU,
  SET_MENU_BUTTON_REF,
  SHOW_SUCCESSFUL_VERIFICATION,
  SHOW_COOKIE_INFO,
  SHOW_CUSTOM_THEME_MODAL,
  CHECK_THEME,
  SET_LIGHT_THEME,
  SET_DARK_THEME,
  SET_CUSTOM_THEME
};
