export enum UserRightsEnum {
  SEND_MESSAGES = "SEND_MESSAGES",
  SEND_FILES = "SEND_FILES",
  ADD_NEW_MEMBERS = "ADD_NEW_MEMBERS",
  DELETE_MEMBERS = "DELETE_MEMBERS",
  CHANGE_RIGHTS_OF_OTHERS = "CHANGE_RIGHTS_OF_OTHERS"
}
